services:
  app:
    image: nodejschatapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3700:3700"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development